server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: user
    password: password
  liquibase:
    default-schema: mod_6
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: app