DROP TABLE IF EXISTS books, authors;

CREATE TABLE  books(
                       id BIGINT generated by default as identity primary key,
                       author_id BIGINT NOT NULL,
                       title VARCHAR(250) NOT NULL,
                       price_old INTEGER DEFAULT NULL,
                       price INTEGER DEFAULT NULL
);

CREATE TABLE authors(
                        id BIGINT generated by default as identity primary key,
                        first_name VARCHAR(64),
                        last_name VARCHAR(64),
                        patronym VARCHAR(64),
                        biography VARCHAR(3000)
);