package com.example.MyBookShopApp.entity.book.entity;

import com.example.MyBookShopApp.entity.book.links.Book2Author;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.Type;
import org.hibernate.proxy.HibernateProxy;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

@ApiModel(description = "data model for author of book entity")
@Getter
@Setter
//@Builder(toBuilder = true)
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "AUTHORS")
public class Author {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "this id is autogenerated by db", position = 1)
    private Long id;

    @Column(name = "first_name")
    @ApiModelProperty(value = "this first name of author", example = "Mike", position = 2)
    private String firstName;

    @ApiModelProperty(value = "this patronym of author", example = "Charly", position = 3)
    private String patronym;

    @Column(name = "last_name")
    @ApiModelProperty(value = "this last name of author", example = "White", position = 4)
    private String lastName;

    @ApiModelProperty(value = "this is biography  of author", position = 5)
    @Type(type = "org.hibernate.type.TextType")
    private String biography;

    @OneToMany(mappedBy = "book")
    @Builder.Default
    @ToString.Exclude
    @JsonIgnore
    private List<Book2Author> booksList = new ArrayList<>();

    @Override
    public final boolean equals(Object o) {
        if (this == o) return true;
        if (o == null) return false;
        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass) return false;
        Author author = (Author) o;
        return getId() != null && Objects.equals(getId(), author.getId());
    }

    @Override
    public final int hashCode() {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }
}

